services:
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "${NGINX_PORT:-80}:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: backend
    env_file:
      - ./backend/.env
    networks:
      - app-network
    volumes:
      - ./audio:/app/audio

networks:
  app-network:
    driver: bridge
