services:
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "${NGINX_PORT:-80}:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: backend
    env_file:
      - ./backend/.env
    networks:
      - app-network
    volumes:
      - ./audio:/app/audio
    depends_on:
      - mfa

  mfa:
    image: mmcauliffe/montreal-forced-aligner:latest
    container_name: mfa
    volumes:
      - ./audio:/app/audio
      - ./mfa/entrypoint.sh:/entrypoint.sh
    entrypoint: ["/bin/bash", "/entrypoint.sh"]
    tty: true
    stdin_open: true
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
