services:
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "${NGINX_PORT:-8080}:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: backend
    env_file:
      - ./backend/.env
    networks:
      - app-network
    volumes:
      - ./audio:/app/audio:rw
      - mfa_tmp_data:/app/tmp_audio:rw
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

networks:
  app-network:
    driver: bridge

volumes:
  mfa_tmp_data:
    driver: local
