services:
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "${NGINX_PORT:-8080}:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: backend
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    networks:
      - app-network
    command: uvicorn app.main:app --host 0.0.0.0 --port 5000 --workers 8

networks:
  app-network:
    driver: bridge
