services:
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "${NGINX_PORT:-80}:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: backend
    env_file:
      - ./backend/.env
    networks:
      - app-network
    volumes:
      - ./audio:/app/audio
    depends_on:
      - mfa
      - ielts

  mfa:
    build: ./mfa
    container_name: mfa
    volumes:
      - ./audio:/app/audio
      - ./mfa/entrypoint.sh:/entrypoint.sh
    entrypoint: ["/bin/bash", "/entrypoint.sh"]
    tty: true
    stdin_open: true
    ports:
      - "5001:5000"
    networks:
      - app-network

  ielts:
    build: ./ielts
    container_name: ielts
    ports:
      - "5002:5000"

networks:
  app-network:
    driver: bridge
