name: ielts
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - requests
      - pydub
      - flask
      - flask_cors
      - numpy
      - datetime
      - gunicorn
      - python-dotenv
      - openai-whisper
      - openai
      - pydantic
      - torch
      - silero-vad
